//WOOJIN CHOI, 10/13/2025
//@version=6
indicator(title = "COT FOTSI",overlay = false)

bool hideCurrentWeek = true
bool showCommercials = true
bool showLarge = true

color_usd = color(#0717ff)
color_eur = color(#4dd0e1)
color_gbp = color(#9C27B0)
color_jpy = color(#FF9800)
color_cad = color(#ff0000)
color_aud = color(#04dd74)
color_nzd = color(#22ab94)
color_chf = color(#E040FB)

color_usd2 = color.new(#0717ff,1)
color_eur2 = color.new(#4dd0e1,1)
color_gbp2 = color.new(#9C27B0,1)
color_jpy2 = color.new(#FF9800,1)
color_cad2 = color.new(#ff0000,1)
color_aud2 = color.new(#04dd74,1)
color_nzd2 = color.new(#22ab94,1)
color_chf2 = color.new(#E040FB,1)
import TradingView/LibraryCOT/2 as cot

var string Root_Symbol = syminfo.root

isForex = syminfo.type == "forex"
var string CFTC_Code_base = isForex ? cot.convertRootToCOTCode("Base currency") : cot.convertRootToCOTCode("Auto") 
var string CFTC_Code_quote =  isForex ? cot.convertRootToCOTCode("Currency")  : cot.convertRootToCOTCode("Auto")

option = input.string("Financial", options = ["Financial", "Legacy"], title="Category", group = "Settings")
legacy_option    = input.string("Noncommercial Positions", options = ["Noncommercial Positions", "Commercial Positions"], title="Legacy", group = "Settings")
financial_option = input.string("Asset Manager Positions", options = ["Leveraged Funds Positions", "Dealer Positions", "Asset Manager Positions"], title="Financial", group = "Settings")

length1 = input.int(1,  title="Momentum period",  minval=0, group= "Settings")
length2 = input.int(25, title="Smoothing period", minval=1, group=  "Settings")
length3 = input.int(15, title="Smoothing period", minval=1, group= "Settings")
slope_length = input.int(2, "Slope Length", group="Settings")

show_all = input.bool(true, "Show All", group="Display")
show_table = input.bool(true, "Show Table",  group="Display")
apply_zero_sum = input.bool(false, "Apply Zero-sum", group = "Display")


dataRequest(code, metricName, direction) =>
    tickerId = cot.COTTickerid(option, code, false, metricName, direction, "All")
    value = request.security(tickerId, "1D", close, ignore_invalid_symbol = true)
    if barstate.islastconfirmedhistory and na(value)
        runtime.error("Could not find relevant COT data based on the current symbol.")
    value


net(code, option) =>
    long = dataRequest(code, option, "Long") 
    short = dataRequest(code, option, "Short")
    long - short

category = option == "Financial" ? financial_option : legacy_option
eur_data = hideCurrentWeek ? (timenow >= time_close ?  net("099741",category) : na) : na
usd_data = hideCurrentWeek ? (timenow >= time_close ?  net("098662",category) : na) : na
gbp_data = hideCurrentWeek ? (timenow >= time_close ?  net("096742",category) : na) : na
chf_data = hideCurrentWeek ? (timenow >= time_close ?  net("092741",category) : na) : na
jpy_data = hideCurrentWeek ? (timenow >= time_close ?  net("097741",category) : na) : na
aud_data = hideCurrentWeek ? (timenow >= time_close ?  net("232741",category) : na) : na
cad_data = hideCurrentWeek ? (timenow >= time_close ?  net("090741",category) : na) : na
nzd_data = hideCurrentWeek ? (timenow >= time_close ?  net("112741",category) : na) : na

eur_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("099741","Open Interest","No direction") : na) : na
usd_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("098662","Open Interest","No direction") : na) : na
gbp_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("096742","Open Interest","No direction") : na) : na
chf_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("092741","Open Interest","No direction") : na) : na
jpy_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("097741","Open Interest","No direction") : na) : na
aud_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("232741","Open Interest","No direction") : na) : na
cad_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("090741","Open Interest","No direction") : na) : na
nzd_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("112741","Open Interest","No direction") : na) : na

mom_usd = usd_data/usd_oi - usd_data[length1]/usd_oi[length1]
mom_eur = eur_data/eur_oi - eur_data[length1]/eur_oi[length1]
mom_gbp = gbp_data/gbp_oi - gbp_data[length1]/gbp_oi[length1]
mom_jpy = jpy_data/jpy_oi - jpy_data[length1]/jpy_oi[length1]
mom_cad = cad_data/cad_oi - cad_data[length1]/cad_oi[length1]
mom_aud = aud_data/aud_oi - aud_data[length1]/aud_oi[length1]
mom_nzd = nzd_data/nzd_oi - nzd_data[length1]/nzd_oi[length1]
mom_chf = chf_data/chf_oi - chf_data[length1]/chf_oi[length1]

invert_dealer = category == "Dealer Positions" or category == "Commercial Positions"
mom_eur := invert_dealer ? -mom_eur : mom_eur
mom_usd := invert_dealer ? -mom_usd : mom_usd
mom_gbp := invert_dealer ? -mom_gbp : mom_gbp
mom_chf := invert_dealer ? -mom_chf : mom_chf
mom_jpy := invert_dealer ? -mom_jpy : mom_jpy
mom_aud := invert_dealer ? -mom_aud : mom_aud
mom_cad := invert_dealer ? -mom_cad : mom_cad
mom_nzd := invert_dealer ? -mom_nzd : mom_nzd

tsi_calc(momentum, length2, length3) =>
    smo1 = ta.ema(momentum, length2)
    smo2 = ta.ema(smo1, length3)
    sma1 = ta.ema(math.abs(momentum), length2)
    sma2 = ta.ema(sma1, length3)
    100 * (smo2 / sma2)

tsi_usd = tsi_calc(mom_usd, length2, length3)
tsi_eur = tsi_calc(mom_eur, length2, length3)
tsi_gbp = tsi_calc(mom_gbp, length2, length3)
tsi_jpy = tsi_calc(mom_jpy, length2, length3)
tsi_cad = tsi_calc(mom_cad, length2, length3)
tsi_aud = tsi_calc(mom_aud, length2, length3)
tsi_nzd = tsi_calc(mom_nzd, length2, length3)
tsi_chf = tsi_calc(mom_chf, length2, length3)

if apply_zero_sum
    tsi_vals = array.from(tsi_eur, tsi_usd, tsi_gbp, tsi_chf, tsi_jpy, tsi_aud, tsi_cad, tsi_nzd)
    tsi_sum = 0.0
    for i = 0 to array.size(tsi_vals) - 1
        tsi_sum += array.get(tsi_vals, i)
    tsi_mean = tsi_sum / array.size(tsi_vals)
    
    tsi_usd -= tsi_mean
    tsi_eur -= tsi_mean
    tsi_gbp -= tsi_mean
    tsi_cad -= tsi_mean
    tsi_jpy -= tsi_mean
    tsi_aud -= tsi_mean
    tsi_nzd -= tsi_mean
    tsi_chf -= tsi_mean

eur_val = tsi_eur
usd_val = tsi_usd
gbp_val = tsi_gbp
chf_val = tsi_chf
jpy_val = tsi_jpy
aud_val = tsi_aud
cad_val = tsi_cad
nzd_val = tsi_nzd
symbol = syminfo.ticker
upperSymbol = str.upper(symbol)
base_currency = str.substring(symbol, 0, 3)     
quote_currency = str.substring(symbol, 3, 6)

show_eur = str.contains(upperSymbol, "EUR")
show_usd = str.contains(upperSymbol, "USD")
show_gbp = str.contains(upperSymbol, "GBP")
show_jpy = str.contains(upperSymbol, "JPY")
show_chf = str.contains(upperSymbol, "CHF")
show_aud = str.contains(upperSymbol, "AUD")
show_cad = str.contains(upperSymbol, "CAD")
show_nzd = str.contains(upperSymbol, "NZD")

plot((show_all or show_eur) ? eur_val : na, title="eur", color=eur_val > eur_val[1] ? color_eur : color_eur2, linewidth=1)
plot((show_all or show_usd) ? usd_val : na, title="usd", color=usd_val > usd_val[1] ? color_usd : color_usd2, linewidth=1)
plot((show_all or show_gbp) ? gbp_val : na, title="gbp", color=gbp_val > gbp_val[1] ? color_gbp : color_gbp2, linewidth=1)
plot((show_all or show_chf) ? chf_val : na, title="chf", color=chf_val > chf_val[1] ? color_chf : color_chf2, linewidth=1)
plot((show_all or show_jpy) ? jpy_val : na, title="jpy", color=jpy_val > jpy_val[1] ? color_jpy : color_jpy2, linewidth=1)
plot((show_all or show_aud) ? aud_val : na, title="aud", color=aud_val > aud_val[1] ? color_aud : color_aud2, linewidth=1)
plot((show_all or show_cad) ? cad_val : na, title="cad", color=cad_val > cad_val[1] ? color_cad : color_cad2, linewidth=1)
plot((show_all or show_nzd) ? nzd_val : na, title="nzd", color=nzd_val > nzd_val[1] ? color_nzd : color_nzd2, linewidth=1)


zero = hline(0, "zero", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)
u1 = hline(50,"upper 1", color=color.rgb(0, 0, 0), linestyle=hline.style_solid)
l1 = hline(-50,"lower 1", color=color.rgb(0, 0, 0), linestyle=hline.style_solid)
u2 = hline(25,"upper 2", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)
l2 = hline(-25,"lower 2", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)
fill(u1,u2, title="top fill", color=color.new(#000000, 93))
fill(l1, l2, title="bot fill", color=color.new(#000000, 93))


slope_eur = (eur_val[1] - eur_val[slope_length+1])
slope_usd = (usd_val[1] - usd_val[slope_length+1])
slope_gbp = (gbp_val[1] - gbp_val[slope_length+1])
slope_chf = (chf_val[1] - chf_val[slope_length+1])
slope_jpy = (jpy_val[1] - jpy_val[slope_length+1])
slope_aud = (aud_val[1] - aud_val[slope_length+1])
slope_cad = (cad_val[1] - cad_val[slope_length+1])
slope_nzd = (nzd_val[1] - nzd_val[slope_length+1])

if show_table and barstate.islast
    var table ranking_table = table.new(position.middle_right, 3, 8, bgcolor=color.white, border_width=1, border_color=color.black)

    currencies = array.new<float>()
    currency_names = array.new<string>()
    currency_colors = array.new<color>()
    slope_values = array.new<float>()

    array.push(currencies, eur_val[1])
    array.push(currency_names, "EUR")
    array.push(slope_values, slope_eur)
    array.push(currency_colors, color_eur)
    
    array.push(currencies, usd_val[1])
    array.push(currency_names, "USD")
    array.push(slope_values, slope_usd)    
    array.push(currency_colors, color_usd)
    
    array.push(currencies, gbp_val[1])
    array.push(currency_names, "GBP")
    array.push(slope_values, slope_gbp)
    array.push(currency_colors, color_gbp)
    
    array.push(currencies, jpy_val[1])
    array.push(currency_names, "JPY")
    array.push(slope_values, slope_jpy)
    array.push(currency_colors, color_jpy)
    
    array.push(currencies, chf_val[1])
    array.push(currency_names, "CHF")
    array.push(slope_values, slope_chf)
    array.push(currency_colors, color_chf)
    
    array.push(currencies, aud_val[1])
    array.push(currency_names, "AUD")
    array.push(slope_values, slope_aud)
    array.push(currency_colors, color_aud)
    
    array.push(currencies, cad_val[1])
    array.push(currency_names, "CAD")
    array.push(slope_values, slope_cad)
    array.push(currency_colors, color_cad)
    
    array.push(currencies, nzd_val[1])
    array.push(currency_names, "NZD")
    array.push(slope_values, slope_nzd)
    array.push(currency_colors, color_nzd)
    
    for i = 0 to array.size(slope_values) - 2
        for j = i + 1 to array.size(slope_values) - 1
            if array.get(slope_values, i) < array.get(slope_values, j)
                temp_rsi = array.get(currencies, i)
                temp_name = array.get(currency_names, i)
                temp_slope = array.get(slope_values,i)
                temp_color = array.get(currency_colors, i)
                
                array.set(currencies, i, array.get(currencies, j))
                array.set(currency_names, i, array.get(currency_names, j))
                array.set(slope_values, i, array.get(slope_values, j))
                array.set(currency_colors, i, array.get(currency_colors, j))
                
                array.set(currencies, j, temp_rsi)
                array.set(currency_names, j, temp_name)
                array.set(slope_values, j, temp_slope)
                array.set(currency_colors, j, temp_color)

    for i = 0 to array.size(currencies) - 1
        name = array.get(currency_names, i)
        tsi_val = array.get(currencies, i)
        slope_value = array.get(slope_values, i)
        curr_color = array.get(currency_colors, i)
        
        tsi_col = tsi_val > 0 ? color.green : tsi_val < 0 ? color.red : color.black
        slope_col = slope_value > 0 ? color.green : slope_value < 0 ? color.red : color.black

        table.cell(ranking_table, 0, i, name, text_color=curr_color, text_size=size.tiny)
        table.cell(ranking_table, 1, i, str.tostring(tsi_val, "#.##"), text_color=tsi_col, text_size=size.tiny)
        table.cell(ranking_table, 2, i, str.tostring(slope_value, "#.##"), text_color=slope_col, text_size=size.tiny)