//WOOJIN CHOI, 8/13/2025
//@version=6
indicator("FX_MACD",shorttitle = "FXMACD", precision=2, overlay=false)

color_eur = color(color.rgb(99, 224, 247))
color_usd = color(#0000ff)
color_gbp = color(color.purple)
color_chf = color(color.fuchsia)
color_jpy = color(color.orange)
color_aud = color(color.lime)
color_cad = color(color.red)
color_nzd = color(color.green)

//============================
fx_src = input.string(title = "FX source", defval = "OANDA", options = ["OANDA", "TASTYFX"])
slow_length = input(title = "Slow Length", defval = 26, group = "Length")
fast_length = input(title = "Fast Length", defval = 12, group = "Length")
signal_length = input(title = "Signal Length", defval = 9, group = "Length")
slope_length = input(title = "Slope Length", defval = 2, group = "Length")
zscore_length = input(title = "Z-score Length", defval = 50, group = "Length")

showAll = input.bool(true, "Show All", group = "Display")
showHistogram = input.bool(false, "Show Histogram", group = "Display")
showTable = input.bool(true, "Show Table", group = "Display")
apply_zero_sum = input.bool(true, "apply_zero_sum", group = "Display")

eurusd_src = "OANDA:EURUSD"
eurgbp_src = "OANDA:EURGBP"
eurchf_src = "OANDA:EURCHF"
eurjpy_src = "OANDA:EURJPY"
euraud_src = "OANDA:EURAUD"
eurcad_src = "OANDA:EURCAD"
eurnzd_src = "OANDA:EURNZD"
usdchf_src = "OANDA:USDCHF"
usdjpy_src = "OANDA:USDJPY"
usdcad_src = "OANDA:USDCAD"
gbpusd_src = "OANDA:GBPUSD"
gbpchf_src = "OANDA:GBPCHF"
gbpjpy_src = "OANDA:GBPJPY"
gbpaud_src = "OANDA:GBPAUD"
gbpcad_src = "OANDA:GBPCAD"
gbpnzd_src = "OANDA:GBPNZD"
chfjpy_src = "OANDA:CHFJPY"
audusd_src = "OANDA:AUDUSD"
audchf_src = "OANDA:AUDCHF"
audjpy_src = "OANDA:AUDJPY"
audcad_src = "OANDA:AUDCAD"
audnzd_src = "OANDA:AUDNZD"
cadchf_src = "OANDA:CADCHF"
cadjpy_src = "OANDA:CADJPY"
nzdusd_src = "OANDA:NZDUSD"
nzdchf_src = "OANDA:NZDCHF"
nzdjpy_src = "OANDA:NZDJPY"
nzdcad_src = "OANDA:NZDCAD"
if fx_src == "TASTYFX"
    eurusd_src := "TASTYFX:EURUSD"
    eurgbp_src := "TASTYFX:EURGBP"
    eurchf_src := "TASTYFX:EURCHF"
    eurjpy_src := "TASTYFX:EURJPY"
    euraud_src := "TASTYFX:EURAUD"
    eurcad_src := "TASTYFX:EURCAD"
    eurnzd_src := "TASTYFX:EURNZD"
    usdchf_src := "TASTYFX:USDCHF"
    usdjpy_src := "TASTYFX:USDJPY"
    usdcad_src := "TASTYFX:USDCAD"
    gbpusd_src := "TASTYFX:GBPUSD"
    gbpchf_src := "TASTYFX:GBPCHF"
    gbpjpy_src := "TASTYFX:GBPJPY"
    gbpaud_src := "TASTYFX:GBPAUD"
    gbpcad_src := "TASTYFX:GBPCAD"
    gbpnzd_src := "TASTYFX:GBPNZD"
    chfjpy_src := "TASTYFX:CHFJPY"
    audusd_src := "TASTYFX:AUDUSD"
    audchf_src := "TASTYFX:AUDCHF"
    audjpy_src := "TASTYFX:AUDJPY"
    audcad_src := "TASTYFX:AUDCAD"
    audnzd_src := "TASTYFX:AUDNZD"
    cadchf_src := "TASTYFX:CADCHF"
    cadjpy_src := "TASTYFX:CADJPY"
    nzdusd_src := "TASTYFX:NZDUSD"
    nzdchf_src := "TASTYFX:NZDCHF"
    nzdjpy_src := "TASTYFX:NZDJPY"
    nzdcad_src := "TASTYFX:NZDCAD"
eurusd = request.security(eurusd_src, timeframe.period, close)
eurgbp = request.security(eurgbp_src, timeframe.period, close)
eurchf = request.security(eurchf_src, timeframe.period, close)
eurjpy = request.security(eurjpy_src, timeframe.period, close) / 100
euraud = request.security(euraud_src, timeframe.period, close)
eurcad = request.security(eurcad_src, timeframe.period, close)
eurnzd = request.security(eurnzd_src, timeframe.period, close)
usdchf = request.security(usdchf_src, timeframe.period, close)
usdjpy = request.security(usdjpy_src, timeframe.period, close) / 100
usdcad = request.security(usdcad_src, timeframe.period, close)
gbpusd = request.security(gbpusd_src, timeframe.period, close)
gbpchf = request.security(gbpchf_src, timeframe.period, close)
gbpjpy = request.security(gbpjpy_src, timeframe.period, close) / 100
gbpaud = request.security(gbpaud_src, timeframe.period, close)
gbpcad = request.security(gbpcad_src, timeframe.period, close)
gbpnzd = request.security(gbpnzd_src, timeframe.period, close)
chfjpy = request.security(chfjpy_src, timeframe.period, close) / 100
audusd = request.security(audusd_src, timeframe.period, close)
audchf = request.security(audchf_src, timeframe.period, close)
audjpy = request.security(audjpy_src, timeframe.period, close) / 100
audcad = request.security(audcad_src, timeframe.period, close)
audnzd = request.security(audnzd_src, timeframe.period, close)
cadchf = request.security(cadchf_src, timeframe.period, close)
cadjpy = request.security(cadjpy_src, timeframe.period, close) / 100
nzdusd = request.security(nzdusd_src, timeframe.period, close)
nzdchf = request.security(nzdchf_src, timeframe.period, close)
nzdjpy = request.security(nzdjpy_src, timeframe.period, close) / 100
nzdcad = request.security(nzdcad_src, timeframe.period, close)

eur = ( eurusd * 0.40 + eurjpy * 0.22 + eurgbp * 0.18 + eurchf * 0.10 + euraud * 0.06 + eurcad * 0.03 + eurnzd * 0.01)
usd = (-eurusd * 0.30 - gbpusd * 0.22 + usdjpy * 0.28 + usdchf * 0.10 - audusd * 0.08 + usdcad * 0.02 - nzdusd * 0.00)
gbp = (-eurgbp * 0.18 + gbpusd * 0.35 + gbpjpy * 0.22 + gbpchf * 0.12 + gbpaud * 0.08 + gbpcad * 0.04 + gbpnzd * 0.01)
chf = (-eurchf * 0.25 - usdchf * 0.35 - gbpchf * 0.20 + chfjpy * 0.10 - audchf * 0.06 - cadchf * 0.03 - nzdchf * 0.01)
jpy = (-eurjpy * 0.22 - usdjpy * 0.35 - gbpjpy * 0.22 - audjpy * 0.12 - cadjpy * 0.06 - chfjpy * 0.02 - nzdjpy * 0.01)
aud = (-euraud * 0.12 + audusd * 0.50 - gbpaud * 0.15 + audchf * 0.08 + audjpy * 0.08 + audcad * 0.05 + audnzd * 0.02)
cad = (-eurcad * 0.08 - usdcad * 0.55 - gbpcad * 0.12 + cadchf * 0.08 + cadjpy * 0.08 - audcad * 0.06 - nzdcad * 0.03)
nzd = (-eurnzd * 0.06 + nzdusd * 0.55 - gbpnzd * 0.12 + nzdchf * 0.08 + nzdjpy * 0.08 - audnzd * 0.08 + nzdcad * 0.03)

zscore(src, length) =>
    mean = ta.ema(src, length)
    stddev = ta.stdev(src, length)
    (src - mean) / stddev

macd_calc(src, fast, slow, sig) =>
    fast_ma = ta.ema(src, fast)
    slow_ma = ta.ema(src, slow)
    macd = zscore(fast_ma - slow_ma, zscore_length)
    signal = ta.ema(macd, sig)
    hist = macd - signal
    [macd,signal,hist]

// adx_calc(symbol) =>
//     high_    = request.security(symbol, timeframe.period, high)
//     low_    = request.security(symbol, timeframe.period, low)
//     up = ta.change(high_)
// 	down = -ta.change(low_)
// 	plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
// 	minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
// 	truerange = ta.rma(ta.tr, 14)
// 	plus = fixnan(100 * ta.rma(plusDM, 14) / truerange)
// 	minus = fixnan(100 * ta.rma(minusDM, 14) / truerange)
// 	sum = plus + minus
// 	adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), 14)

[macd_eur,sig_eur,hist_eur] = macd_calc(eur,fast_length,slow_length,signal_length)
[macd_usd,sig_usd,hist_usd] = macd_calc(usd,fast_length,slow_length,signal_length)
[macd_gbp,sig_gbp,hist_gbp] = macd_calc(gbp,fast_length,slow_length,signal_length)
[macd_chf,sig_chf,hist_chf] = macd_calc(chf,fast_length,slow_length,signal_length)
[macd_jpy,sig_jpy,hist_jpy] = macd_calc(jpy,fast_length,slow_length,signal_length)
[macd_aud,sig_aud,hist_aud] = macd_calc(aud,fast_length,slow_length,signal_length)
[macd_cad,sig_cad,hist_cad] = macd_calc(cad,fast_length,slow_length,signal_length)
[macd_nzd,sig_nzd,hist_nzd] = macd_calc(nzd,fast_length,slow_length,signal_length)

sumMacd = macd_eur + macd_usd + macd_gbp + macd_chf + macd_jpy + macd_aud + macd_cad + macd_nzd
sumSig = sig_eur + sig_usd + sig_gbp + sig_chf + sig_jpy + sig_aud + sig_cad + sig_nzd
sumHist = hist_eur + hist_usd + hist_gbp + hist_chf + hist_jpy + hist_aud + hist_cad + hist_nzd
if apply_zero_sum
    macd_eur := macd_eur - sumMacd/8
    macd_usd := macd_usd - sumMacd/8
    macd_gbp := macd_gbp - sumMacd/8
    macd_chf := macd_chf - sumMacd/8
    macd_jpy := macd_jpy - sumMacd/8
    macd_aud := macd_aud - sumMacd/8
    macd_cad := macd_cad - sumMacd/8
    macd_nzd := macd_nzd - sumMacd/8
    sig_eur := sig_eur - sumSig/8
    sig_usd := sig_usd - sumSig/8
    sig_gbp := sig_gbp - sumSig/8
    sig_chf := sig_chf - sumSig/8
    sig_jpy := sig_jpy - sumSig/8
    sig_aud := sig_aud - sumSig/8
    sig_cad := sig_cad - sumSig/8
    sig_nzd := sig_nzd - sumSig/8
    hist_eur := hist_eur - sumHist/8
    hist_usd := hist_usd - sumHist/8
    hist_gbp := hist_gbp - sumHist/8
    hist_chf := hist_chf - sumHist/8
    hist_jpy := hist_jpy - sumHist/8
    hist_aud := hist_aud - sumHist/8
    hist_cad := hist_cad - sumHist/8
    hist_nzd := hist_nzd - sumHist/8

symbol = syminfo.ticker
upperSymbol = str.upper(symbol)

showEUR = str.contains(upperSymbol, "EUR")
showUSD = str.contains(upperSymbol, "USD")
showGBP = str.contains(upperSymbol, "GBP")
showJPY = str.contains(upperSymbol, "JPY")
showCHF = str.contains(upperSymbol, "CHF")
showAUD = str.contains(upperSymbol, "AUD")
showCAD = str.contains(upperSymbol, "CAD")
showNZD = str.contains(upperSymbol, "NZD")

macd_plot_eur = plot(showEUR or showAll ? macd_eur : na, title="EUR macd", color= color_eur, linewidth=2)
macd_plot_usd = plot(showUSD or showAll ? macd_usd : na, title="USD macd", color= color_usd, linewidth=2)
macd_plot_gbp = plot(showGBP or showAll ? macd_gbp : na, title="GBP macd", color= color_gbp, linewidth=2)
macd_plot_chf = plot(showCHF or showAll ? macd_chf : na, title="CHF macd", color= color_chf, linewidth=2)
macd_plot_jpy = plot(showJPY or showAll ? macd_jpy : na, title="JPY macd", color= color_jpy, linewidth=2)
macd_plot_aud = plot(showAUD or showAll ? macd_aud : na, title="AUD macd", color= color_aud, linewidth=2)
macd_plot_cad = plot(showCAD or showAll ? macd_cad : na, title="CAD macd", color= color_cad, linewidth=2)
macd_plot_nzd = plot(showNZD or showAll ? macd_nzd : na, title="NZD macd", color= color_nzd, linewidth=2)

sig_plot_eur = plot(showEUR or showAll ? sig_eur : na, title="EUR sig", color= color.new(color_eur,70), linewidth=1)
sig_plot_usd = plot(showUSD or showAll ? sig_usd : na, title="USD sig", color= color.new(color_usd,70), linewidth=1)
sig_plot_gbp = plot(showGBP or showAll ? sig_gbp : na, title="GBP sig", color= color.new(color_gbp,70), linewidth=1)
sig_plot_chf = plot(showCHF or showAll ? sig_chf : na, title="CHF sig", color= color.new(color_chf,70), linewidth=1)
sig_plot_jpy = plot(showJPY or showAll ? sig_jpy : na, title="JPY sig", color= color.new(color_jpy,70), linewidth=1)
sig_plot_aud = plot(showAUD or showAll ? sig_aud : na, title="AUD sig", color= color.new(color_aud,70), linewidth=1)
sig_plot_cad = plot(showCAD or showAll ? sig_cad : na, title="CAD sig", color= color.new(color_cad,70), linewidth=1)
sig_plot_nzd = plot(showNZD or showAll ? sig_nzd : na, title="NZD sig", color= color.new(color_nzd,70), linewidth=1)

fill(macd_plot_eur,sig_plot_eur, title="eur plot", color=color.new(color_eur,80))
fill(macd_plot_usd,sig_plot_usd, title="usd plot", color=color.new(color_usd,80))
fill(macd_plot_gbp,sig_plot_gbp, title="gbp plot", color=color.new(color_gbp,80))
fill(macd_plot_chf,sig_plot_chf, title="chf plot", color=color.new(color_chf,80))
fill(macd_plot_jpy,sig_plot_jpy, title="jpy plot", color=color.new(color_jpy,80))
fill(macd_plot_aud,sig_plot_aud, title="aud plot", color=color.new(color_aud,80))
fill(macd_plot_cad,sig_plot_cad, title="cad plot", color=color.new(color_cad,80))
fill(macd_plot_nzd,sig_plot_nzd, title="nzd plot", color=color.new(color_nzd,80))

// plot(sig_eur+sig_usd+sig_gbp+sig_chf+sig_jpy+sig_aud+sig_cad+sig_nzd)
// plot(macd_eur+macd_usd+macd_gbp+macd_chf+macd_jpy+macd_aud+macd_cad+macd_nzd)
// plot(hist_eur+hist_usd+hist_gbp+hist_chf+hist_jpy+hist_aud+hist_cad+hist_nzd)
plot((showEUR or showAll) and showHistogram ? hist_eur : na, title="EUR hist", color= showEUR ? color.new(color_eur,40) : color.new(color_eur,40), linewidth=1, style = plot.style_columns)
plot((showUSD or showAll) and showHistogram ? hist_usd : na, title="USD hist", color= showUSD ? color.new(color_usd,40) : color.new(color_usd,40), linewidth=1, style = plot.style_columns)
plot((showGBP or showAll) and showHistogram ? hist_gbp : na, title="GBP hist", color= showGBP ? color.new(color_gbp,40) : color.new(color_gbp,40), linewidth=1, style = plot.style_columns)
plot((showCHF or showAll) and showHistogram ? hist_chf : na, title="CHF hist", color= showCHF ? color.new(color_chf,40) : color.new(color_chf,40), linewidth=1, style = plot.style_columns)
plot((showJPY or showAll) and showHistogram ? hist_jpy : na, title="JPY hist", color= showJPY ? color.new(color_jpy,40) : color.new(color_jpy,40), linewidth=1, style = plot.style_columns)
plot((showAUD or showAll) and showHistogram ? hist_aud : na, title="AUD hist", color= showAUD ? color.new(color_aud,40) : color.new(color_aud,40), linewidth=1, style = plot.style_columns)
plot((showCAD or showAll) and showHistogram ? hist_cad : na, title="CAD hist", color= showCAD ? color.new(color_cad,40) : color.new(color_cad,40), linewidth=1, style = plot.style_columns)
plot((showNZD or showAll) and showHistogram ? hist_nzd : na, title="NZD hist", color= showNZD ? color.new(color_nzd,40) : color.new(color_nzd,40), linewidth=1, style = plot.style_columns)

u1 = hline(2, "2,upper", color=color.rgb(0, 0, 0), linestyle=hline.style_solid)
l1 =hline(-2, "-2,lower", color=color.rgb(0, 0, 0), linestyle=hline.style_solid)
u2 = hline(3, "3,upper", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)
l2 = hline(-3, "-3,lower", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)
zero = hline(0, "zero", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)

fill(u1,u2, title="top", color=color.new(color.gray, 85))
fill(l1, l2, title="bottom", color=color.new(color.gray, 85))


slope_eur = (macd_eur*10 - macd_eur[slope_length]*10)
slope_usd = (macd_usd*10 - macd_usd[slope_length]*10)
slope_gbp = (macd_gbp*10 - macd_gbp[slope_length]*10)
slope_chf = (macd_chf*10 - macd_chf[slope_length]*10)
slope_jpy = (macd_jpy*10 - macd_jpy[slope_length]*10)
slope_aud = (macd_aud*10 - macd_aud[slope_length]*10)
slope_cad = (macd_cad*10 - macd_cad[slope_length]*10)
slope_nzd = (macd_nzd*10 - macd_nzd[slope_length]*10)
//--------------------------------------------------TABLE
if showTable and barstate.islast
    var table ranking_table = table.new(position.middle_right, 3, 8, bgcolor=color.white, border_width=1, border_color=color.black)

    currencies = array.new<float>()
    currency_names = array.new<string>()
    currency_colors = array.new<color>()
    slope_values = array.new<float>()

    array.push(currencies, macd_eur)
    array.push(currency_names, "EUR")
    array.push(slope_values, slope_eur)
    array.push(currency_colors, color_eur)
    
    array.push(currencies, macd_usd)
    array.push(currency_names, "USD")
    array.push(slope_values, slope_usd)    
    array.push(currency_colors, color_usd)
    
    array.push(currencies, macd_gbp)
    array.push(currency_names, "GBP")
    array.push(slope_values, slope_gbp)
    array.push(currency_colors, color_gbp)
    
    array.push(currencies, macd_jpy)
    array.push(currency_names, "JPY")
    array.push(slope_values, slope_jpy)
    array.push(currency_colors, color_jpy)
    
    array.push(currencies, macd_chf)
    array.push(currency_names, "CHF")
    array.push(slope_values, slope_chf)
    array.push(currency_colors, color_chf)
    
    array.push(currencies, macd_aud)
    array.push(currency_names, "AUD")
    array.push(slope_values, slope_aud)
    array.push(currency_colors, color_aud)
    
    array.push(currencies, macd_cad)
    array.push(currency_names, "CAD")
    array.push(slope_values, slope_cad)
    array.push(currency_colors, color_cad)
    
    array.push(currencies, macd_nzd)
    array.push(currency_names, "NZD")
    array.push(slope_values, slope_nzd)
    array.push(currency_colors, color_nzd)
    
    for i = 0 to array.size(slope_values) - 2
        for j = i + 1 to array.size(slope_values) - 1
            if array.get(slope_values, i) < array.get(slope_values, j)
                temp_macd = array.get(currencies, i)
                temp_name = array.get(currency_names, i)
                temp_slope = array.get(slope_values,i)
                temp_color = array.get(currency_colors, i)
                
                array.set(currencies, i, array.get(currencies, j))
                array.set(currency_names, i, array.get(currency_names, j))
                array.set(slope_values, i, array.get(slope_values, j))
                array.set(currency_colors, i, array.get(currency_colors, j))
                
                array.set(currencies, j, temp_macd)
                array.set(currency_names, j, temp_name)
                array.set(slope_values, j, temp_slope)
                array.set(currency_colors, j, temp_color)

    for i = 0 to array.size(currencies) - 1
        name = array.get(currency_names, i)
        macd_val = array.get(currencies, i)
        slope_value = array.get(slope_values, i)
        curr_color = array.get(currency_colors, i)
        
        macd_col = macd_val > 0 ? color.green : macd_val < 0 ? color.red : color.black
        slope_col = slope_value > 0 ? color.green : slope_value < 0 ? color.red : color.black

        table.cell(ranking_table, 0, i, name, text_color=curr_color, text_size=size.tiny)
        table.cell(ranking_table, 1, i, str.tostring(macd_val, "#.##"), text_color=macd_col, text_size=size.tiny)
        table.cell(ranking_table, 2, i, str.tostring(slope_value, "#.##"), text_color=slope_col, text_size=size.tiny)
