//@version=6
indicator("FX_RSI", shorttitle = "FXRSI",precision=2, overlay=false)

color_eur = color(color.blue)
color_usd = color(#0000ff)
color_gbp = color(color.purple)
color_chf = color(color.fuchsia)
color_jpy = color(color.orange)
color_aud = color(color.lime)
color_cad = color(color.red)
color_nzd = color(color.green)

color_eur2 = color(color.rgb(30, 147, 243))
color_usd2 = color(#0e0efa)
color_gbp2 = color(color.rgb(151, 35, 172))
color_chf2 = color(color.rgb(222, 56, 252))
color_jpy2 = color(color.rgb(231, 140, 4))
color_aud2 = color(color.rgb(4, 221, 116))
color_cad2 = color(color.rgb(250, 70, 70))
color_nzd2 = color(color.rgb(75, 179, 78))
fx_src = input.string("OANDA", title ="FX source", options = ["OANDA", "TASTYFX"])
eurusd_src = "OANDA:EURUSD"
eurgbp_src = "OANDA:EURGBP"
eurchf_src = "OANDA:EURCHF"
eurjpy_src = "OANDA:EURJPY"
euraud_src = "OANDA:EURAUD"
eurcad_src = "OANDA:EURCAD"
eurnzd_src = "OANDA:EURNZD"
usdchf_src = "OANDA:USDCHF"
usdjpy_src = "OANDA:USDJPY"
usdcad_src = "OANDA:USDCAD"
gbpusd_src = "OANDA:GBPUSD"
gbpchf_src = "OANDA:GBPCHF"
gbpjpy_src = "OANDA:GBPJPY"
gbpaud_src = "OANDA:GBPAUD"
gbpcad_src = "OANDA:GBPCAD"
gbpnzd_src = "OANDA:GBPNZD"
chfjpy_src = "OANDA:CHFJPY"
audusd_src = "OANDA:AUDUSD"
audchf_src = "OANDA:AUDCHF"
audjpy_src = "OANDA:AUDJPY"
audcad_src = "OANDA:AUDCAD"
audnzd_src = "OANDA:AUDNZD"
cadchf_src = "OANDA:CADCHF"
cadjpy_src = "OANDA:CADJPY"
nzdusd_src = "OANDA:NZDUSD"
nzdchf_src = "OANDA:NZDCHF"
nzdjpy_src = "OANDA:NZDJPY"
nzdcad_src = "OANDA:NZDCAD"
if fx_src == "TASTYFX"
    eurusd_src := "TASTYFX:EURUSD"
    eurgbp_src := "TASTYFX:EURGBP"
    eurchf_src := "TASTYFX:EURCHF"
    eurjpy_src := "TASTYFX:EURJPY"
    euraud_src := "TASTYFX:EURAUD"
    eurcad_src := "TASTYFX:EURCAD"
    eurnzd_src := "TASTYFX:EURNZD"
    usdchf_src := "TASTYFX:USDCHF"
    usdjpy_src := "TASTYFX:USDJPY"
    usdcad_src := "TASTYFX:USDCAD"
    gbpusd_src := "TASTYFX:GBPUSD"
    gbpchf_src := "TASTYFX:GBPCHF"
    gbpjpy_src := "TASTYFX:GBPJPY"
    gbpaud_src := "TASTYFX:GBPAUD"
    gbpcad_src := "TASTYFX:GBPCAD"
    gbpnzd_src := "TASTYFX:GBPNZD"
    chfjpy_src := "TASTYFX:CHFJPY"
    audusd_src := "TASTYFX:AUDUSD"
    audchf_src := "TASTYFX:AUDCHF"
    audjpy_src := "TASTYFX:AUDJPY"
    audcad_src := "TASTYFX:AUDCAD"
    audnzd_src := "TASTYFX:AUDNZD"
    cadchf_src := "TASTYFX:CADCHF"
    cadjpy_src := "TASTYFX:CADJPY"
    nzdusd_src := "TASTYFX:NZDUSD"
    nzdchf_src := "TASTYFX:NZDCHF"
    nzdjpy_src := "TASTYFX:NZDJPY"
    nzdcad_src := "TASTYFX:NZDCAD"
eurusd = request.security(eurusd_src, timeframe.period, close)
eurgbp = request.security(eurgbp_src, timeframe.period, close)
eurchf = request.security(eurchf_src, timeframe.period, close)
eurjpy = request.security(eurjpy_src, timeframe.period, close) / 100
euraud = request.security(euraud_src, timeframe.period, close)
eurcad = request.security(eurcad_src, timeframe.period, close)
eurnzd = request.security(eurnzd_src, timeframe.period, close)
usdchf = request.security(usdchf_src, timeframe.period, close)
usdjpy = request.security(usdjpy_src, timeframe.period, close) / 100
usdcad = request.security(usdcad_src, timeframe.period, close)
gbpusd = request.security(gbpusd_src, timeframe.period, close)
gbpchf = request.security(gbpchf_src, timeframe.period, close)
gbpjpy = request.security(gbpjpy_src, timeframe.period, close) / 100
gbpaud = request.security(gbpaud_src, timeframe.period, close)
gbpcad = request.security(gbpcad_src, timeframe.period, close)
gbpnzd = request.security(gbpnzd_src, timeframe.period, close)
chfjpy = request.security(chfjpy_src, timeframe.period, close) / 100
audusd = request.security(audusd_src, timeframe.period, close)
audchf = request.security(audchf_src, timeframe.period, close)
audjpy = request.security(audjpy_src, timeframe.period, close) / 100
audcad = request.security(audcad_src, timeframe.period, close)
audnzd = request.security(audnzd_src, timeframe.period, close)
cadchf = request.security(cadchf_src, timeframe.period, close)
cadjpy = request.security(cadjpy_src, timeframe.period, close) / 100
nzdusd = request.security(nzdusd_src, timeframe.period, close)
nzdchf = request.security(nzdchf_src, timeframe.period, close)
nzdjpy = request.security(nzdjpy_src, timeframe.period, close) / 100
nzdcad = request.security(nzdcad_src, timeframe.period, close)

eur = ( eurusd * 0.40 + eurjpy * 0.22 + eurgbp * 0.18 + eurchf * 0.10 + euraud * 0.06 + eurcad * 0.03 + eurnzd * 0.01)
usd = (-eurusd * 0.30 - gbpusd * 0.22 + usdjpy * 0.28 + usdchf * 0.10 - audusd * 0.08 + usdcad * 0.02 - nzdusd * 0.00)
gbp = (-eurgbp * 0.18 + gbpusd * 0.35 + gbpjpy * 0.22 + gbpchf * 0.12 + gbpaud * 0.08 + gbpcad * 0.04 + gbpnzd * 0.01)
chf = (-eurchf * 0.25 - usdchf * 0.35 - gbpchf * 0.20 + chfjpy * 0.10 - audchf * 0.06 - cadchf * 0.03 - nzdchf * 0.01)
jpy = (-eurjpy * 0.22 - usdjpy * 0.35 - gbpjpy * 0.22 - audjpy * 0.12 - cadjpy * 0.06 - chfjpy * 0.02 - nzdjpy * 0.01)
aud = (-euraud * 0.12 + audusd * 0.50 - gbpaud * 0.15 + audchf * 0.08 + audjpy * 0.08 + audcad * 0.05 + audnzd * 0.02)
cad = (-eurcad * 0.08 - usdcad * 0.55 - gbpcad * 0.12 + cadchf * 0.08 + cadjpy * 0.08 - audcad * 0.06 - nzdcad * 0.03)
nzd = (-eurnzd * 0.06 + nzdusd * 0.55 - gbpnzd * 0.12 + nzdchf * 0.08 + nzdjpy * 0.08 - audnzd * 0.08 + nzdcad * 0.03)


lengthRSI = input(title = "RSI Length", defval = 10, group = "Length")
lengthFast = input.int(5, title="Fast Length", group = "Length")  
lengthSlow = input.int(21, title="Slow Length", group = "Length")
lengthSignal = input.int(8, title="Signal Length", group = "Length")
lengthSlope = input.int(2, "Slope Length", group = "Length")
lengthZscore = input.int(50, "Z-Score Length", group = "Length")
showAll = input.bool(true, "Show All", group = "Display")
showTable = input.bool(true, "Show Table", group = "Display")
apply_zero_sum = input.bool(true, "apply_zero_sum", group = "Display")

zscore(src, length) =>
    mean = ta.ema(src, length)
    stddev = ta.stdev(src, length)
    (src - mean) / stddev

rsi_macd_calc(src, fast, slow, sig) =>
    fast_ma = ta.ema(src, fast)
    slow_ma = ta.ema(src, slow)
    macd = zscore(fast_ma - slow_ma,lengthZscore)
    signal = ta.ema(macd, sig)
    rsi_val = ta.rsi(signal, lengthRSI)
    rsi_val

rsi_eur = rsi_macd_calc(eur, lengthFast, lengthSlow, lengthSignal)
rsi_usd = rsi_macd_calc(usd, lengthFast, lengthSlow, lengthSignal)
rsi_gbp = rsi_macd_calc(gbp, lengthFast, lengthSlow, lengthSignal)
rsi_chf = rsi_macd_calc(chf, lengthFast, lengthSlow, lengthSignal)
rsi_jpy = rsi_macd_calc(jpy, lengthFast, lengthSlow, lengthSignal)
rsi_aud = rsi_macd_calc(aud, lengthFast, lengthSlow, lengthSignal)
rsi_cad = rsi_macd_calc(cad, lengthFast, lengthSlow, lengthSignal)
rsi_nzd = rsi_macd_calc(nzd, lengthFast, lengthSlow, lengthSignal)

sumRSI = rsi_eur + rsi_usd + rsi_gbp + rsi_chf + rsi_jpy + rsi_aud + rsi_cad + rsi_nzd
if apply_zero_sum
    rsi_eur := rsi_eur - sumRSI/8 + 50
    rsi_usd := rsi_usd - sumRSI/8 + 50
    rsi_gbp := rsi_gbp - sumRSI/8 + 50
    rsi_chf := rsi_chf - sumRSI/8 + 50
    rsi_jpy := rsi_jpy - sumRSI/8 + 50
    rsi_aud := rsi_aud - sumRSI/8 + 50
    rsi_cad := rsi_cad - sumRSI/8 + 50
    rsi_nzd := rsi_nzd - sumRSI/8 + 50

symbol = syminfo.ticker
upperSymbol = str.upper(symbol)

showEUR = str.contains(upperSymbol, "EUR")
showUSD = str.contains(upperSymbol, "USD")
showGBP = str.contains(upperSymbol, "GBP")
showJPY = str.contains(upperSymbol, "JPY")
showCHF = str.contains(upperSymbol, "CHF")
showAUD = str.contains(upperSymbol, "AUD")
showCAD = str.contains(upperSymbol, "CAD")
showNZD = str.contains(upperSymbol, "NZD")

eur_20 = ta.ema(eur,14)
usd_20 = ta.ema(usd,14)
gbp_20 = ta.ema(gbp,14)
chf_20 = ta.ema(chf,14)
jpy_20 = ta.ema(jpy,14)
aud_20 = ta.ema(aud,14)
cad_20 = ta.ema(cad,14)
nzd_20 = ta.ema(nzd,14)

slope_eur = (rsi_eur - rsi_eur[lengthSlope])
slope_usd = (rsi_usd - rsi_usd[lengthSlope])
slope_gbp = (rsi_gbp - rsi_gbp[lengthSlope])
slope_chf = (rsi_chf - rsi_chf[lengthSlope])
slope_jpy = (rsi_jpy - rsi_jpy[lengthSlope])
slope_aud = (rsi_aud - rsi_aud[lengthSlope])
slope_cad = (rsi_cad - rsi_cad[lengthSlope])
slope_nzd = (rsi_nzd - rsi_nzd[lengthSlope])

plot(showEUR or showAll ? rsi_eur : na, title="EUR", color= (eur_20 < eur and slope_eur > 0) or (eur_20 > eur and slope_eur < 0) ? color_eur : color_eur2, linewidth=1)
plot(showUSD or showAll ? rsi_usd : na, title="USD", color= (usd_20 < usd and slope_usd > 0) or (usd_20 > usd and slope_usd < 0) ? color_usd : color_usd2, linewidth=1)
plot(showGBP or showAll ? rsi_gbp : na, title="GBP", color= (gbp_20 < gbp and slope_gbp > 0) or (gbp_20 > gbp and slope_gbp < 0) ? color_gbp : color_gbp2, linewidth=1)
plot(showCHF or showAll ? rsi_chf : na, title="CHF", color= (chf_20 < chf and slope_chf > 0) or (chf_20 > chf and slope_chf < 0) ? color_chf : color_chf2, linewidth=1)
plot(showJPY or showAll ? rsi_jpy : na, title="JPY", color= (jpy_20 < jpy and slope_jpy > 0) or (jpy_20 > jpy and slope_jpy < 0) ? color_jpy : color_jpy2, linewidth=1)
plot(showAUD or showAll ? rsi_aud : na, title="AUD", color= (aud_20 < aud and slope_aud > 0) or (aud_20 > aud and slope_aud < 0) ? color_aud : color_aud2, linewidth=1)
plot(showCAD or showAll ? rsi_cad : na, title="CAD", color= (cad_20 < cad and slope_cad > 0) or (cad_20 > cad and slope_cad < 0) ? color_cad : color_cad2, linewidth=1)
plot(showNZD or showAll ? rsi_nzd : na, title="NZD", color= (nzd_20 < nzd and slope_nzd > 0) or (nzd_20 > nzd and slope_nzd < 0) ? color_nzd : color_nzd2, linewidth=1)
//plot(rsi_eur-50+rsi_usd-50+rsi_gbp-50+rsi_chf-50+rsi_jpy-50+rsi_aud-50+rsi_cad-50+rsi_nzd-50)
u1 = hline(80, "upper1", color=color.rgb(0, 0, 0), linestyle=hline.style_solid)
l1 =hline(20, "lower1", color=color.rgb(0, 0, 0), linestyle=hline.style_solid)
u2 = hline(90, "upper2", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)
l2 = hline(10, "lower2", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)
zero = hline(50, "zero", color=color.rgb(0, 0, 0), linestyle=hline.style_dotted)
fill(u1,u2, title="top", color=color.new(color.gray, 85))
fill(l1, l2, title="bottom", color=color.new(color.gray, 85))

if showTable and barstate.islast
    var table ranking_table = table.new(position.middle_right, 3, 8, bgcolor=color.white, border_width=1, border_color=color.black)

    currencies = array.new<float>()
    currency_names = array.new<string>()
    currency_colors = array.new<color>()
    slope_values = array.new<float>()

    array.push(currencies, rsi_eur)
    array.push(currency_names, "EUR")
    array.push(slope_values, slope_eur)
    array.push(currency_colors, color_eur)
    
    array.push(currencies, rsi_usd)
    array.push(currency_names, "USD")
    array.push(slope_values, slope_usd)    
    array.push(currency_colors, color_usd)
    
    array.push(currencies, rsi_gbp)
    array.push(currency_names, "GBP")
    array.push(slope_values, slope_gbp)
    array.push(currency_colors, color_gbp)
    
    array.push(currencies, rsi_jpy)
    array.push(currency_names, "JPY")
    array.push(slope_values, slope_jpy)
    array.push(currency_colors, color_jpy)
    
    array.push(currencies, rsi_chf)
    array.push(currency_names, "CHF")
    array.push(slope_values, slope_chf)
    array.push(currency_colors, color_chf)
    
    array.push(currencies, rsi_aud)
    array.push(currency_names, "AUD")
    array.push(slope_values, slope_aud)
    array.push(currency_colors, color_aud)
    
    array.push(currencies, rsi_cad)
    array.push(currency_names, "CAD")
    array.push(slope_values, slope_cad)
    array.push(currency_colors, color_cad)
    
    array.push(currencies, rsi_nzd)
    array.push(currency_names, "NZD")
    array.push(slope_values, slope_nzd)
    array.push(currency_colors, color_nzd)
    
    // 정렬
    for i = 0 to array.size(slope_values) - 2
        for j = i + 1 to array.size(slope_values) - 1
            if array.get(slope_values, i) < array.get(slope_values, j)
                temp_rsi = array.get(currencies, i)
                temp_name = array.get(currency_names, i)
                temp_slope = array.get(slope_values,i)
                temp_color = array.get(currency_colors, i)
                
                array.set(currencies, i, array.get(currencies, j))
                array.set(currency_names, i, array.get(currency_names, j))
                array.set(slope_values, i, array.get(slope_values, j))
                array.set(currency_colors, i, array.get(currency_colors, j))
                
                array.set(currencies, j, temp_rsi)
                array.set(currency_names, j, temp_name)
                array.set(slope_values, j, temp_slope)
                array.set(currency_colors, j, temp_color)

    for i = 0 to array.size(currencies) - 1
        name = array.get(currency_names, i)
        rsi_val = array.get(currencies, i)
        slope_value = array.get(slope_values, i)
        curr_color = array.get(currency_colors, i)
        
        rsi_col = rsi_val > 50 ? color.green : rsi_val < 50 ? color.red : color.black
        slope_col = slope_value > 0 ? color.green : slope_value < 0 ? color.red : color.black

        table.cell(ranking_table, 0, i, name, text_color=curr_color, text_size=size.tiny)
        table.cell(ranking_table, 1, i, str.tostring(rsi_val, "#.##"), text_color=rsi_col, text_size=size.tiny)
        table.cell(ranking_table, 2, i, str.tostring(slope_value, "#.##"), text_color=slope_col, text_size=size.tiny)