//WOOJIN CHOI, 9/29/2025
//@version=6
indicator("MA Ribbon", shorttitle="MAribbon", overlay=true, timeframe="", timeframe_gaps=true)

ma(source, length, type) =>
    type == "SMA" ? ta.sma(source, length) : type == "EMA" ? ta.ema(source, length) : type == "WMA" ? ta.wma(source, length) : type == "HMA" ? ta.wma(2 * ta.wma(source, length / 2) - ta.wma(source, length), math.round(math.sqrt(length))) : na

show_ma1   = input(true   , "MA #1", inline="MA #1", display = display.data_window)
ma1_type   = input.string("EMA"  , ""     , inline="MA #1", options=["SMA", "EMA", "WMA", "HMA"])
ma1_source = input(close  , ""     , inline="MA #1", display = display.data_window)
ma1_length = input.int(25     , ""     , inline="MA #1", minval=1)
ma1 = ma(ma1_source, ma1_length, ma1_type)

show_ma2   = input(true   , "MA #2", inline="MA #2", display = display.data_window)
ma2_type   = input.string("EMA"  , ""     , inline="MA #2", options=["SMA", "EMA", "WMA", "HMA"])
ma2_source = input(close  , ""     , inline="MA #2", display = display.data_window)
ma2_length = input.int(50     , ""     , inline="MA #2", minval=1)
ma2 = ma(ma2_source, ma2_length, ma2_type)

show_ma3   = input(true   , "MA #3", inline="MA #3", display = display.data_window)
ma3_type   = input.string("EMA"  , ""     , inline="MA #3", options=["SMA", "EMA", "WMA", "HMA"])
ma3_source = input(close  , ""     , inline="MA #3", display = display.data_window)
ma3_length = input.int(100    , ""     , inline="MA #3", minval=1)
ma3 = ma(ma3_source, ma3_length, ma3_type)

show_ma4   = input(false   , "MA #4", inline="MA #4", display = display.data_window)
ma4_type   = input.string("EMA"  , ""     , inline="MA #4", options=["SMA", "EMA", "WMA", "HMA"])
ma4_source = input(close  , ""     , inline="MA #4", display = display.data_window)
ma4_length = input.int(200    , ""     , inline="MA #4", minval=1)
ma4 = ma(ma4_source, ma4_length, ma4_type)

check_bullish(len) =>
    bull = ma1[len] > ma2[len] and ma1[len] > ma3[len] and ma2[len] > ma3[len]
    bull
check_bearish(len) =>
    bear =  ma1[len] < ma2[len] and ma1[len] < ma3[len] and ma2[len] < ma3[len]
    bear

bool bullish = check_bullish(0)
bool bearish = check_bearish(0)

ma1_color = color.blue 
ma2_color = color.teal 
ma3_color = color.red
ma4_color = color.purple

plot(show_ma1 ? ma1 : na, color = ma1_color, title="MA #1", linewidth = 2,linestyle = plot.linestyle_dotted)
plot(show_ma2 ? ma2 : na, color = ma2_color, title="MA #2", linewidth = 2,linestyle = plot.linestyle_dotted)
plot(show_ma3 ? ma3 : na, color = ma3_color, title="MA #3", linewidth = 2,linestyle = plot.linestyle_dotted)
plot(show_ma4 ? ma4 : na, color = ma4_color, title="MA #4", linewidth = 2,linestyle = plot.linestyle_dotted)

// long = not check_bullish(1) and bullish
// short = not check_bearish(1) and bearish
// plotshape(long, "long",shape.circle,location.belowbar, color.teal, size = size.tiny, display = display.all - display.status_line)
// plotshape(short, "short",shape.circle,location.abovebar,color.red, size = size.tiny , display = display.all - display.status_line)

// alertcondition(long or short, "MA Ribbon Signal", "MA Ribbon Signal")