//WOOJIN CHOI, 10/06/2025
//@version=6
indicator("Currency Strength Complex Common Frames percent","CS_CCFp")

mode      = input.string("EMA","MA_Method", options = ["SMA","EMA","SMMA","LWMA"],group = "settings")
option    = input.string("default", options = ["default", "velocity", "acceleration", "jerk"],group = "settings")
src       = input.source(ohlc4,"Price",group = "settings")
fastlen   = input.int( 3,"Fast",minval = 1, maxval = 50,group = "length")
slowlen   = input.int( 5,"Slow",minval = 2, maxval = 100,group = "length")
len_vel = input.int(3, "velocity length",group = "length")
len_accel = input.int(6, "acceleration length",group = "length")
len_impul = input.int(9, "impulse length",group = "length")
len_jerk = input.int(9, "jerk length",group = "length")


show_only_pair = input.bool(false, "Show Pair",group = "display")
show_table = input.bool(true, "Show Table",group = "display")

usd   = input.bool(true,inline = "c1",title = "USD",group="calc")
eur   = input.bool(true,inline = "c1",title = "EUR",group="calc")
gbp   = input.bool(true,inline = "c2",title = "GBP",group="calc")
aud   = input.bool(true,inline = "c2",title = "AUD",group="calc")
nzd   = input.bool(true,inline = "c3",title = "NZD",group="calc")
cad   = input.bool(true,inline = "c3",title = "CAD",group="calc")
chf   = input.bool(true,inline = "c4",title = "CHF",group="calc")
jpy   = input.bool(true,inline = "c4",title = "JPY",group="calc")

sym1 = syminfo.basecurrency
sym2 = syminfo.currency

tf        = timeframe.period

timeframe_(tf_) =>
    ret = switch tf_
        "1"   => 1 
        "5"   => 5
        "15"  => 15 
        "30"  => 30 
        "60"  => 60 
        "120"  => 120 
        "180"  => 180 
        "240" => 240
        "480" => 480
        "720" => 720
        "1D"   => 1440 
        "2D"   => 2800 
        "3D"   => 4320 
        "1W"   => 10080
        "1M"   => 43200
        => na
    ret

int time_frame = timeframe_(tf)

color_usd = color(#0717ff)
color_eur = color(#4dd0e1)
color_gbp = color(#9C27B0)
color_jpy = color(#FF9800)
color_cad = color(#ff0000)
color_aud = color(#04dd74)
color_nzd = color(#22ab94)
color_chf = color(#E040FB)
 
eurusd = request.security("OANDA:EURUSD",tf,src)
gbpusd = request.security("OANDA:GBPUSD",tf,src)
audusd = request.security("OANDA:AUDUSD",tf,src)
nzdusd = request.security("OANDA:NZDUSD",tf,src)
usdcad = request.security("OANDA:USDCAD",tf,src)
usdchf = request.security("OANDA:USDCHF",tf,src)
usdjpy = request.security("OANDA:USDJPY",tf,src)


lwma(src,period) =>
    float p = na
    float sum = 0
    float divider = period * (period + 1) / 2
    for i = 0 to period-1
        p := src[i] * (period - i)
        sum := sum + p
    sum / divider

smma(src,period) =>
    ret_val = 0.0
    sma_1 = ta.sma(src, period)
    ret_val := na(ret_val[1]) ? sma_1 : (ret_val[1] * (period - 1) + src) / period
    
    ret_val

ma(source,str,period,time_frame) =>
    float ret_val = 0
    k = 1
    if str == "SMA"
        if time_frame <= 1
            ret_val := ret_val + ta.sma(source,period*k)
            k += 5
        if time_frame <= 5
            ret_val := ret_val + ta.sma(source,period*k)
            k += 3
        if time_frame <= 15
            ret_val := ret_val + ta.sma(source,period*k)
            k += 2
        if time_frame <= 30
            ret_val := ret_val + ta.sma(source,period*k)
            k += 2
        if time_frame <= 60
            ret_val := ret_val + ta.sma(source,period*k)
            k += 4
        if time_frame <= 240
            ret_val := ret_val + ta.sma(source,period*k)
            k += 6
        if time_frame <= 1440
            ret_val := ret_val + ta.sma(source,period*k)
            k += 4
        if time_frame <= 10080
            ret_val := ret_val + ta.sma(source,period*k)
            k += 4
        if time_frame <= 43200
            ret_val := ret_val + ta.sma(source,period*k)
            
    if str == "EMA"
        if time_frame <= 1
            ret_val := ret_val + ta.ema(source,period*k)
            k += 5
        if time_frame <= 5
            ret_val := ret_val + ta.ema(source,period*k)
            k += 3
        if time_frame <= 15
            ret_val := ret_val + ta.ema(source,period*k)
            k += 2
        if time_frame <= 30
            ret_val := ret_val + ta.ema(source,period*k)
            k += 2
        if time_frame <= 60
            ret_val := ret_val + ta.ema(source,period*k)
            k += 4
        if time_frame <= 240
            ret_val := ret_val + ta.ema(source,period*k)
            k += 6
        if time_frame <= 1440
            ret_val := ret_val + ta.ema(source,period*k)
            k += 4
        if time_frame <= 10080
            ret_val := ret_val + ta.ema(source,period*k)
            k += 4
        if time_frame <= 43200
            ret_val := ret_val + ta.ema(source,period*k)

    if str == "SMMA"
        if time_frame <= 1
            ret_val := ret_val + smma(source,period*k)
            k += 5
        if time_frame <= 5
            ret_val := ret_val + smma(source,period*k)
            k += 3
        if time_frame <= 15
            ret_val := ret_val + smma(source,period*k)
            k += 2
        if time_frame <= 30
            ret_val := ret_val + smma(source,period*k)
            k += 2
        if time_frame <= 60
            ret_val := ret_val + smma(source,period*k)
            k += 4
        if time_frame <= 240
            ret_val := ret_val + smma(source,period*k)
            k += 6
        if time_frame <= 1440
            ret_val := ret_val + smma(source,period*k)
            k += 4
        if time_frame <= 10080
            ret_val := ret_val + smma(source,period*k)
            k += 4
        if time_frame <= 43200
            ret_val := ret_val + smma(source,period*k)
 
    if str == "LWMA"
        if time_frame <= 1
            ret_val := ret_val + lwma(source,period*k)
            k += 5
        if time_frame <= 5
            ret_val := ret_val + lwma(source,period*k)
            k += 3
        if time_frame <= 15
            ret_val := ret_val + lwma(source,period*k)
            k += 2
        if time_frame <= 30
            ret_val := ret_val + lwma(source,period*k)
            k += 2
        if time_frame <= 60
            ret_val := ret_val + lwma(source,period*k)
            k += 4
        if time_frame <= 240
            ret_val := ret_val + lwma(source,period*k)
            k += 6
        if time_frame <= 1440
            ret_val := ret_val + lwma(source,period*k)
            k += 4
        if time_frame <= 10080
            ret_val := ret_val + lwma(source,period*k)
            k += 4
        if time_frame <= 43200
            ret_val := ret_val + lwma(source,period*k)
    ret_val

CalcCCFP(ticker,eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast) =>
    float ccfp_idx = 0.0

    if ticker == "USD"
        if eur
            ccfp_idx += eurusd_slow / eurusd_fast - 1
        if gbp
            ccfp_idx += gbpusd_slow / gbpusd_fast - 1
        if aud
            ccfp_idx += audusd_slow / audusd_fast - 1
        if nzd
            ccfp_idx += nzdusd_slow / nzdusd_fast - 1
        if chf
            ccfp_idx += usdchf_fast / usdchf_slow - 1
        if cad
            ccfp_idx += usdcad_fast / usdcad_slow - 1
        if jpy
            ccfp_idx += usdjpy_fast / usdjpy_slow - 1
            
    else if ticker == "EUR"
        if usd
            ccfp_idx += eurusd_fast / eurusd_slow - 1
        if gbp
            ccfp_idx += (eurusd_fast / gbpusd_fast) / (eurusd_slow/gbpusd_slow) - 1
        if aud
            ccfp_idx += (eurusd_fast / audusd_fast) / (eurusd_slow/audusd_slow) - 1
        if nzd
            ccfp_idx += (eurusd_fast / nzdusd_fast) / (eurusd_slow/nzdusd_slow) - 1
        if chf
            ccfp_idx += (eurusd_fast * usdchf_fast) / (eurusd_slow * usdchf_slow) - 1
        if cad
            ccfp_idx += (eurusd_fast * usdcad_fast) / (eurusd_slow * usdcad_slow) - 1
        if jpy
            ccfp_idx += (eurusd_fast * usdjpy_fast) / (eurusd_slow * usdjpy_slow) - 1
    
    else if ticker == "GBP"
        if usd
            ccfp_idx += gbpusd_fast / gbpusd_slow - 1
        if eur
            ccfp_idx += (eurusd_slow / gbpusd_slow) / (eurusd_fast / gbpusd_fast) - 1
        if aud
            ccfp_idx += (gbpusd_fast / audusd_fast) / (gbpusd_slow / audusd_slow) - 1
        if nzd
            ccfp_idx += (gbpusd_fast / nzdusd_fast) / (gbpusd_slow / nzdusd_slow) - 1
        if chf
            ccfp_idx += (gbpusd_fast * usdchf_fast) / (gbpusd_slow * usdchf_slow) - 1
        if cad
            ccfp_idx += (gbpusd_fast * usdcad_fast) / (gbpusd_slow * usdcad_slow) - 1
        if jpy
            ccfp_idx += (gbpusd_fast * usdjpy_fast) / (gbpusd_slow * usdjpy_slow) - 1
    
    else if ticker == "AUD"
        if usd
            ccfp_idx += audusd_fast / audusd_slow - 1
        if eur
            ccfp_idx += (eurusd_slow / audusd_slow) / (eurusd_fast / audusd_fast) - 1
        if gbp
            ccfp_idx += (gbpusd_slow / audusd_slow) / (gbpusd_fast / audusd_fast) - 1
        if nzd
            ccfp_idx += (audusd_fast / nzdusd_fast) / (audusd_slow / nzdusd_slow) - 1
        if chf
            ccfp_idx += (audusd_fast * usdchf_fast) / (audusd_slow * usdchf_slow) - 1
        if cad
            ccfp_idx += (audusd_fast * usdcad_fast) / (audusd_slow * usdcad_slow) - 1
        if jpy
            ccfp_idx += (audusd_fast * usdjpy_fast) / (audusd_slow * usdjpy_slow) - 1
    
    else if ticker == "NZD"
        if usd
            ccfp_idx += nzdusd_fast / nzdusd_slow - 1
        if eur
            ccfp_idx += (eurusd_slow / nzdusd_slow) / (eurusd_fast / nzdusd_fast) - 1
        if gbp
            ccfp_idx += (gbpusd_slow / nzdusd_slow) / (gbpusd_fast / nzdusd_fast) - 1
        if aud
            ccfp_idx += (audusd_slow / nzdusd_slow) / (audusd_fast / nzdusd_fast) - 1
        if chf
            ccfp_idx += (nzdusd_fast * usdchf_fast) / (nzdusd_slow * usdchf_slow) - 1
        if cad
            ccfp_idx += (nzdusd_fast * usdcad_fast) / (nzdusd_slow * usdcad_slow) - 1
        if jpy
            ccfp_idx += (nzdusd_fast * usdjpy_fast) / (nzdusd_slow * usdjpy_slow) - 1
    
    else if ticker == "CAD"
        if usd
            ccfp_idx += usdcad_slow / usdcad_fast - 1
        if eur
            ccfp_idx += (eurusd_slow * usdcad_slow) / (eurusd_fast * usdcad_fast) - 1
        if gbp
            ccfp_idx += (gbpusd_slow * usdcad_slow) / (gbpusd_fast * usdcad_fast) - 1
        if aud
            ccfp_idx += (audusd_slow * usdcad_slow) / (audusd_fast * usdcad_fast) - 1
        if nzd
            ccfp_idx += (nzdusd_slow * usdcad_slow) / (nzdusd_fast * usdcad_fast) - 1
        if chf
            ccfp_idx += (usdchf_fast / usdcad_fast) / (usdchf_slow / usdcad_slow) - 1
        if jpy
            ccfp_idx += (usdjpy_fast / usdcad_fast) / (usdjpy_slow / usdcad_slow) - 1
    
    else if ticker == "CHF"
        if usd
            ccfp_idx += usdchf_slow / usdchf_fast - 1
        if eur
            ccfp_idx += (eurusd_slow * usdchf_slow) / (eurusd_fast * usdchf_fast) - 1
        if gbp
            ccfp_idx += (gbpusd_slow * usdchf_slow) / (gbpusd_fast * usdchf_fast) - 1
        if aud
            ccfp_idx += (audusd_slow * usdchf_slow) / (audusd_fast * usdchf_fast) - 1
        if nzd
            ccfp_idx += (nzdusd_slow * usdchf_slow) / (nzdusd_fast * usdchf_fast) - 1
        if cad
            ccfp_idx += (usdchf_slow / usdcad_slow) / (usdchf_fast / usdcad_fast) - 1
        if jpy
            ccfp_idx += (usdjpy_fast / usdchf_fast) / (usdjpy_slow / usdchf_slow) - 1
    
    else if ticker == "JPY"
        if usd
            ccfp_idx += usdjpy_slow / usdjpy_fast - 1
        if eur
            ccfp_idx += (eurusd_slow * usdjpy_slow) / (eurusd_fast * usdjpy_fast) - 1
        if gbp
            ccfp_idx += (gbpusd_slow * usdjpy_slow) / (gbpusd_fast * usdjpy_fast) - 1
        if aud
            ccfp_idx += (audusd_slow * usdjpy_slow) / (audusd_fast * usdjpy_fast) - 1
        if nzd
            ccfp_idx += (nzdusd_slow * usdjpy_slow) / (nzdusd_fast * usdjpy_fast) - 1
        if cad
            ccfp_idx += (usdjpy_slow / usdcad_slow) / (usdjpy_fast / usdcad_fast) - 1
        if chf
            ccfp_idx += (usdjpy_slow / usdchf_slow) / (usdjpy_fast / usdchf_fast) - 1
    
        
    ccfp_idx

show_usd = show_only_pair ? (sym1 == "USD" or sym2 == "USD") and usd :usd
show_eur = show_only_pair ? (sym1 == "EUR" or sym2 == "EUR") and eur :eur
show_gbp = show_only_pair ? (sym1 == "GBP" or sym2 == "GBP") and gbp :gbp
show_aud = show_only_pair ? (sym1 == "AUD" or sym2 == "AUD") and aud :aud
show_nzd = show_only_pair ? (sym1 == "NZD" or sym2 == "NZD") and nzd :nzd
show_cad = show_only_pair ? (sym1 == "CAD" or sym2 == "CAD") and cad :cad
show_chf = show_only_pair ? (sym1 == "CHF" or sym2 == "CHF") and chf :chf
show_jpy = show_only_pair ? (sym1 == "JPY" or sym2 == "JPY") and jpy :jpy

eurusd_slow = eur ? ma(eurusd,mode,slowlen,time_frame) : na
eurusd_fast = eur ? ma(eurusd,mode,fastlen,time_frame) : na
gbpusd_slow = gbp ? ma(gbpusd,mode,slowlen,time_frame) : na
gbpusd_fast = gbp ? ma(gbpusd,mode,fastlen,time_frame) : na
audusd_slow = aud ? ma(audusd,mode,slowlen,time_frame) : na
audusd_fast = aud ? ma(audusd,mode,fastlen,time_frame) : na
nzdusd_slow = nzd ? ma(nzdusd,mode,slowlen,time_frame) : na
nzdusd_fast = nzd ? ma(nzdusd,mode,fastlen,time_frame) : na
usdchf_slow = chf ? ma(usdchf,mode,slowlen,time_frame) : na
usdchf_fast = chf ? ma(usdchf,mode,fastlen,time_frame) : na
usdcad_slow = cad ? ma(usdcad,mode,slowlen,time_frame) : na
usdcad_fast = cad ? ma(usdcad,mode,fastlen,time_frame) : na
usdjpy_slow = jpy ? ma(usdjpy,mode,slowlen,time_frame) : na
usdjpy_fast = jpy ? ma(usdjpy,mode,fastlen,time_frame) : na

USD = CalcCCFP("USD",eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast)
EUR = CalcCCFP("EUR",eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast)
GBP = CalcCCFP("GBP",eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast)
AUD = CalcCCFP("AUD",eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast)
NZD = CalcCCFP("NZD",eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast)
CAD = CalcCCFP("CAD",eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast)
CHF = CalcCCFP("CHF",eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast)
JPY = CalcCCFP("JPY",eurusd,gbpusd,audusd,nzdusd,usdchf,usdcad,usdjpy,usd,eur,gbp,aud,nzd,chf,cad,jpy,eurusd_slow,eurusd_fast,gbpusd_slow,gbpusd_fast,audusd_slow,audusd_fast,nzdusd_slow,nzdusd_fast,usdchf_slow,usdchf_fast,usdcad_slow,usdcad_fast,usdjpy_slow,usdjpy_fast)

mean = USD+EUR+GBP+AUD+NZD+CAD+CHF+JPY
USD -= mean
EUR -= mean
GBP -= mean
AUD -= mean
NZD -= mean
CAD -= mean
CHF -= mean
JPY -= mean


USD_vel = USD - USD[len_vel]
EUR_vel = EUR - EUR[len_vel]
GBP_vel = GBP - GBP[len_vel]
AUD_vel = AUD - AUD[len_vel]
NZD_vel = NZD - NZD[len_vel]
CAD_vel = CAD - CAD[len_vel]
CHF_vel = CHF - CHF[len_vel]
JPY_vel = JPY - JPY[len_vel]

USD_accel = USD_vel - USD_vel[len_accel]
EUR_accel = EUR_vel - EUR_vel[len_accel]
GBP_accel = GBP_vel - GBP_vel[len_accel]
AUD_accel = AUD_vel - AUD_vel[len_accel]
NZD_accel = NZD_vel - NZD_vel[len_accel]
CAD_accel = CAD_vel - CAD_vel[len_accel]
CHF_accel = CHF_vel - CHF_vel[len_accel]
JPY_accel = JPY_vel - JPY_vel[len_accel]

USD_jerk = USD_accel - USD_accel[len_jerk]
EUR_jerk = EUR_accel - EUR_accel[len_jerk]
GBP_jerk = GBP_accel - GBP_accel[len_jerk]
AUD_jerk = AUD_accel - AUD_accel[len_jerk]
NZD_jerk = NZD_accel - NZD_accel[len_jerk]
CAD_jerk = CAD_accel - CAD_accel[len_jerk]
CHF_jerk = CHF_accel - CHF_accel[len_jerk]
JPY_jerk = JPY_accel - JPY_accel[len_jerk]

calc_impulse (accel, len)=>
    float sum = 0
    for i = 0 to len
        sum += accel[i]
    
    avg = sum/len

USD_impul = calc_impulse(USD_accel, len_impul)
EUR_impul = calc_impulse(EUR_accel, len_impul)
GBP_impul = calc_impulse(GBP_accel, len_impul)
AUD_impul = calc_impulse(AUD_accel, len_impul)
NZD_impul = calc_impulse(NZD_accel, len_impul)
CAD_impul = calc_impulse(CAD_accel, len_impul)
CHF_impul = calc_impulse(CHF_accel, len_impul)
JPY_impul = calc_impulse(JPY_accel, len_impul)
USD_val = option == "default" ? USD : option == "velocity" ? USD_vel : option == "acceleration" ? USD_accel : option == "impulse"?USD_impul  : option == "jerk" ? USD_jerk: na 
EUR_val = option == "default" ? EUR : option == "velocity" ? EUR_vel : option == "acceleration" ? EUR_accel : option == "impulse"?EUR_impul  : option == "jerk" ? EUR_jerk: na 
GBP_val = option == "default" ? GBP : option == "velocity" ? GBP_vel : option == "acceleration" ? GBP_accel : option == "impulse"?GBP_impul  : option == "jerk" ? GBP_jerk: na 
AUD_val = option == "default" ? AUD : option == "velocity" ? AUD_vel : option == "acceleration" ? AUD_accel : option == "impulse"?AUD_impul  : option == "jerk" ? AUD_jerk: na 
NZD_val = option == "default" ? NZD : option == "velocity" ? NZD_vel : option == "acceleration" ? NZD_accel : option == "impulse"?NZD_impul  : option == "jerk" ? NZD_jerk: na 
CAD_val = option == "default" ? CAD : option == "velocity" ? CAD_vel : option == "acceleration" ? CAD_accel : option == "impulse"?CAD_impul  : option == "jerk" ? CAD_jerk: na 
CHF_val = option == "default" ? CHF : option == "velocity" ? CHF_vel : option == "acceleration" ? CHF_accel : option == "impulse"?CHF_impul  : option == "jerk" ? CHF_jerk: na 
JPY_val = option == "default" ? JPY : option == "velocity" ? JPY_vel : option == "acceleration" ? JPY_accel : option == "impulse"?JPY_impul  : option == "jerk" ? JPY_jerk: na 
plot(show_usd ? USD_val : na,title = "USD",color = color_usd,linewidth= 2)
plot(show_eur ? EUR_val : na,title = "EUR",color = color_eur,linewidth= 2)
plot(show_gbp ? GBP_val : na,title = "GBP",color = color_gbp,linewidth= 2)
plot(show_aud ? AUD_val : na,title = "AUD",color = color_aud,linewidth= 2)
plot(show_nzd ? NZD_val : na,title = "NZD",color = color_nzd,linewidth= 2)
plot(show_cad ? CAD_val : na,title = "CAD",color = color_cad,linewidth= 2)
plot(show_chf ? CHF_val : na,title = "CHF",color = color_chf,linewidth= 2)
plot(show_jpy ? JPY_val : na,title = "JPY",color = color_jpy,linewidth= 2)
hline(0,"zero",color.black,hline.style_dotted)

var table symbolDisplay = table.new(position.bottom_right, 1, 1)

if show_table and barstate.islast
    color TEXT_COLOR = color.white
    color BG_COLOR = color.new(color.black, 50)
    color WARN_COLOR = color.new(color.orange, 30)
    
    string header = str.format("{0}", option)
    
    // Header
    table.cell(symbolDisplay, 0, 0, header, text_halign=text.align_right, text_color=TEXT_COLOR, bgcolor=BG_COLOR, text_size=size.tiny)