//WOOJIN CHOI, 9/29/2025
//@version=6
bool hideCurrentWeek = true
bool showCommercials = true
bool showLarge = true
color_eur = color(color.blue)
color_usd = color(#0000ff)
color_gbp = color(color.purple)
color_chf = color(color.fuchsia)
color_jpy = color(color.orange)
color_aud = color(color.lime)
color_cad = color(color.red)
color_nzd = color(color.green)

indicator("COT FX", shorttitle="FXCOT")

import TradingView/LibraryCOT/2 as cot

var string Root_Symbol = syminfo.root

isForex = syminfo.type == "forex"
var string CFTC_Code_base = isForex ? cot.convertRootToCOTCode("Base currency") : cot.convertRootToCOTCode("Auto") 
var string CFTC_Code_quote =  isForex ? cot.convertRootToCOTCode("Currency")  : cot.convertRootToCOTCode("Auto")

// string legacy_option    = input.string("Noncommercial Positions", options = ["Noncommercial Positions", "Commercial Positions"], title="Legacy")
// string financial_option = input.string("Leveraged Funds Positions", options = ["Leveraged Funds Positions", "Dealer Positions", "Asset Manager Positions"], title="Financial")

dataRequest(code, metricName, direction) =>
    tickerId = cot.COTTickerid("Financial", code, false, metricName, direction, "All")
    value = request.security(tickerId, "1D", close, ignore_invalid_symbol = true)
    if barstate.islastconfirmedhistory and na(value)
        runtime.error("Could not find relevant COT data based on the current symbol.")
    value

// Calculates net long positions for commercials
net(code, option) =>
    long = dataRequest(code, option, "Long") 
    short = dataRequest(code, option, "Short")
    long - short
//
eur_lev = hideCurrentWeek ? (timenow >= time_close ?  net("099741","Asset Manager Positions") : na) : na
usd_lev = hideCurrentWeek ? (timenow >= time_close ?  net("098662","Asset Manager Positions") : na) : na
gbp_lev = hideCurrentWeek ? (timenow >= time_close ?  net("096742","Asset Manager Positions") : na) : na
chf_lev = hideCurrentWeek ? (timenow >= time_close ?  net("092741","Asset Manager Positions") : na) : na
jpy_lev = hideCurrentWeek ? (timenow >= time_close ?  net("097741","Asset Manager Positions") : na) : na
aud_lev = hideCurrentWeek ? (timenow >= time_close ?  net("232741","Asset Manager Positions") : na) : na
cad_lev = hideCurrentWeek ? (timenow >= time_close ?  net("090741","Asset Manager Positions") : na) : na
nzd_lev = hideCurrentWeek ? (timenow >= time_close ?  net("112741","Asset Manager Positions") : na) : na

eur_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("099741","Open Interest","No direction") : na) : na
usd_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("098662","Open Interest","No direction") : na) : na
gbp_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("096742","Open Interest","No direction") : na) : na
chf_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("092741","Open Interest","No direction") : na) : na
jpy_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("097741","Open Interest","No direction") : na) : na
aud_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("232741","Open Interest","No direction") : na) : na
cad_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("090741","Open Interest","No direction") : na) : na
nzd_oi = hideCurrentWeek ? (timenow >= time_close ?  dataRequest("112741","Open Interest","No direction") : na) : na


zscore_length = input.int(52, "z-score length")
slope_length = input.int(2, "slope length")
smoothing = input.bool(true, "smoothing")
show_all = input.bool(true, "show all")
show_table = input.bool(true, "show table")
zscore(src, length) =>
    mean = ta.sma(src, length)
    stddev = ta.stdev(src, length)
    (src - mean) / stddev

eur_ = zscore(eur_lev/eur_oi,zscore_length)
usd_ = zscore(usd_lev/usd_oi,zscore_length)
gbp_ = zscore(gbp_lev/gbp_oi,zscore_length)
chf_ = zscore(chf_lev/chf_oi,zscore_length)
jpy_ = zscore(jpy_lev/jpy_oi,zscore_length)
aud_ = zscore(aud_lev/aud_oi,zscore_length)
cad_ = zscore(cad_lev/cad_oi,zscore_length)
nzd_ = zscore(nzd_lev/nzd_oi,zscore_length)

eur_ema = ta.ema(eur_,3)
usd_ema = ta.ema(usd_,3)
gbp_ema = ta.ema(gbp_,3)
chf_ema = ta.ema(chf_,3)
jpy_ema = ta.ema(jpy_,3)
aud_ema = ta.ema(aud_,3)
cad_ema = ta.ema(cad_,3)
nzd_ema = ta.ema(nzd_,3)

eur_val = smoothing ? eur_ema : eur_
usd_val = smoothing ? usd_ema : usd_
gbp_val = smoothing ? gbp_ema : gbp_
chf_val = smoothing ? chf_ema : chf_
jpy_val = smoothing ? jpy_ema : jpy_
aud_val = smoothing ? aud_ema : aud_
cad_val = smoothing ? cad_ema : cad_
nzd_val = smoothing ? nzd_ema : nzd_

symbol = syminfo.ticker
upperSymbol = str.upper(symbol)
base_currency = str.substring(symbol, 0, 3)     
quote_currency = str.substring(symbol, 3, 6)

show_eur = str.contains(upperSymbol, "EUR")
show_usd = str.contains(upperSymbol, "USD")
show_gbp = str.contains(upperSymbol, "GBP")
show_jpy = str.contains(upperSymbol, "JPY")
show_chf = str.contains(upperSymbol, "CHF")
show_aud = str.contains(upperSymbol, "AUD")
show_cad = str.contains(upperSymbol, "CAD")
show_nzd = str.contains(upperSymbol, "NZD")
plot((show_all or show_eur) ? eur_val : na, title="eur", color=color_eur, linewidth=1)
plot((show_all or show_usd) ? usd_val : na, title="usd", color=color_usd, linewidth=1)
plot((show_all or show_gbp) ? gbp_val : na, title="gbp", color=color_gbp, linewidth=1)
plot((show_all or show_chf) ? chf_val : na, title="chf", color=color_chf, linewidth=1)
plot((show_all or show_jpy) ? jpy_val : na, title="jpy", color=color_jpy, linewidth=1)
plot((show_all or show_aud) ? aud_val : na, title="aud", color=color_aud, linewidth=1)
plot((show_all or show_cad) ? cad_val : na, title="cad", color=color_cad, linewidth=1)
plot((show_all or show_nzd) ? nzd_val : na, title="nzd", color=color_nzd, linewidth=1)


hline(0.0,color = color.black)
u1 = hline(2.0,color = color.black, linestyle = hline.style_dotted)
l1 = hline(-2.0,color = color.black, linestyle = hline.style_dotted)
u2 = hline(3.0,color = color.black, linestyle = hline.style_solid)
l2 = hline(-3.0,color = color.black, linestyle = hline.style_solid)
fill(u1,u2,color = color.rgb(255, 82, 82, 60))
fill(l1,l2,color= color.rgb(76, 175, 79, 60))


slope_eur = (eur_val[1] - eur_val[slope_length+1])
slope_usd = (usd_val[1] - usd_val[slope_length+1])
slope_gbp = (gbp_val[1] - gbp_val[slope_length+1])
slope_chf = (chf_val[1] - chf_val[slope_length+1])
slope_jpy = (jpy_val[1] - jpy_val[slope_length+1])
slope_aud = (aud_val[1] - aud_val[slope_length+1])
slope_cad = (cad_val[1] - cad_val[slope_length+1])
slope_nzd = (nzd_val[1] - nzd_val[slope_length+1])

if show_table and barstate.islast
    var table ranking_table = table.new(position.middle_right, 3, 8, bgcolor=color.white, border_width=1, border_color=color.black)

    currencies = array.new<float>()
    currency_names = array.new<string>()
    currency_colors = array.new<color>()
    slope_values = array.new<float>()

    array.push(currencies, eur_val[1])
    array.push(currency_names, "EUR")
    array.push(slope_values, slope_eur)
    array.push(currency_colors, color_eur)
    
    array.push(currencies, usd_val[1])
    array.push(currency_names, "USD")
    array.push(slope_values, slope_usd)    
    array.push(currency_colors, color_usd)
    
    array.push(currencies, gbp_val[1])
    array.push(currency_names, "GBP")
    array.push(slope_values, slope_gbp)
    array.push(currency_colors, color_gbp)
    
    array.push(currencies, jpy_val[1])
    array.push(currency_names, "JPY")
    array.push(slope_values, slope_jpy)
    array.push(currency_colors, color_jpy)
    
    array.push(currencies, chf_val[1])
    array.push(currency_names, "CHF")
    array.push(slope_values, slope_chf)
    array.push(currency_colors, color_chf)
    
    array.push(currencies, aud_val[1])
    array.push(currency_names, "AUD")
    array.push(slope_values, slope_aud)
    array.push(currency_colors, color_aud)
    
    array.push(currencies, cad_val[1])
    array.push(currency_names, "CAD")
    array.push(slope_values, slope_cad)
    array.push(currency_colors, color_cad)
    
    array.push(currencies, nzd_val[1])
    array.push(currency_names, "NZD")
    array.push(slope_values, slope_nzd)
    array.push(currency_colors, color_nzd)
    
    for i = 0 to array.size(slope_values) - 2
        for j = i + 1 to array.size(slope_values) - 1
            if array.get(slope_values, i) < array.get(slope_values, j)
                temp_rsi = array.get(currencies, i)
                temp_name = array.get(currency_names, i)
                temp_slope = array.get(slope_values,i)
                temp_color = array.get(currency_colors, i)
                
                array.set(currencies, i, array.get(currencies, j))
                array.set(currency_names, i, array.get(currency_names, j))
                array.set(slope_values, i, array.get(slope_values, j))
                array.set(currency_colors, i, array.get(currency_colors, j))
                
                array.set(currencies, j, temp_rsi)
                array.set(currency_names, j, temp_name)
                array.set(slope_values, j, temp_slope)
                array.set(currency_colors, j, temp_color)

    for i = 0 to array.size(currencies) - 1
        name = array.get(currency_names, i)
        tsi_val = array.get(currencies, i)
        slope_value = array.get(slope_values, i)
        curr_color = array.get(currency_colors, i)
        
        tsi_col = tsi_val > 0 ? color.green : tsi_val < 0 ? color.red : color.black
        slope_col = slope_value > 0 ? color.green : slope_value < 0 ? color.red : color.black

        table.cell(ranking_table, 0, i, name, text_color=curr_color, text_size=size.tiny)
        table.cell(ranking_table, 1, i, str.tostring(tsi_val, "#.##"), text_color=tsi_col, text_size=size.tiny)
        table.cell(ranking_table, 2, i, str.tostring(slope_value, "#.##"), text_color=slope_col, text_size=size.tiny)