// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cdw1432t

//@version=6
indicator("DI", overlay=true)

hf_timeframe = input.timeframe("60", title="Higher Timeframe")
di_len = input.int(75, "SMA Length")
di_min = input.float(0.25, "DI min")
di_max = input.float(3, "DI max")
is_label = input.bool(false)

hf_ha_close = request.security(syminfo.tickerid, hf_timeframe, close)
hf_ema_val = ta.sma(hf_ha_close, di_len)
dist = hf_ha_close - hf_ema_val
percent_dist = (100 * (close - hf_ema_val) / hf_ema_val)
higher_ = request.security(syminfo.tickerid, "D", close)
Dema = ta.sma(higher_, di_len)
dema_percent_dist = (100 * (close - Dema) / Dema)

bear_di = (di_min <= percent_dist and percent_dist <= di_max) // 캔들이 평균선 위에서 괴리율, 역)매도 신호
bull_di = (-di_max <= percent_dist and percent_dist <= -di_min) //캔들이 평균선 아래에서 괴리율, 역)매수 신호

//AREA
body_area_above = close > hf_ema_val ? close - hf_ema_val : 0
body_area_below = close < hf_ema_val ? hf_ema_val - close : 0

var float area_sum_above = na
var float area_sum_below = na
area_sum_above := nz(area_sum_above)
area_sum_below := nz(area_sum_below)

// === AREA UP
if close > hf_ema_val
    area_sum_above += body_area_above
else
    if area_sum_above > 0 and is_label
        label.new(bar_index,low,text = str.tostring(area_sum_above*1000, "##.##"),style = label.style_label_up,color = color.new(color.green, 0),textcolor = color.white)
    area_sum_above := 0.0

// === AREA DOWN
if close < hf_ema_val
    area_sum_below += body_area_below
else
    if area_sum_below > 0 and is_label
        label.new(bar_index,high,text = str.tostring(area_sum_below*1000, "##.##"), style = label.style_label_down,color = color.new(color.red, 0),textcolor = color.white)
    area_sum_below := 0.0

p_close = plot(close, title="Close", color=color.new(color.blue, 0), style=plot.style_linebr, display = display.none)
p_ema = plot(hf_ema_val, title="EMA", color=color.new(color.red, 0))
p_dema = plot(Dema, title="DEMA", color=color.new(color.blue, 0))
fill(p_close, p_dema, color = close > Dema ? color.new(color.green, 90) : color.new(color.red, 90))

is_local_top = high >= ta.highest(high, 3)
is_local_bottom = low <= ta.lowest(low, 3)

rsi = ta.rsi(close, 13)
buySignal = bull_di and is_local_bottom and rsi < 30 
sellSignal = bear_di and is_local_top and rsi > 70

plotshape(buySignal , title="Buy Signal", location=location.belowbar, style=shape.circle, color=color.rgb(155, 39, 176, 55), size=size.small)
plotshape(sellSignal , title="Buy Signal", location=location.abovebar, style=shape.circle, color=color.rgb(155, 39, 176, 55), size=size.small)

potential_resis_buy = 0.0 < dema_percent_dist and dema_percent_dist < 0.03
potential_resis_sell = -0.03 < dema_percent_dist and dema_percent_dist < -0.0
plotshape(potential_resis_buy , title="potential_resis_buy Signal", location=location.belowbar, style=shape.circle, color=color.new(color.green, 88), size=size.tiny)
plotshape(potential_resis_sell , title="potential_resis_buy Signal", location=location.abovebar, style=shape.circle, color=color.new(color.red,88), size=size.tiny)
// ALERTS
alertcondition(buySignal, title="BUY ALERT", message="DI Buy Signal")
alertcondition(sellSignal, title="SELL ALERT", message="DI Sell Signal")
alertcondition(sellSignal or buySignal, title="BUY OR SELL ALERT", message="DI Signal")