// @version=6
indicator("Heikin Ashi", overlay=true, max_labels_count=500)

// === INPUTS ===
ha_timeframe = input.timeframe("3", title="Timeframe")
hf_timeframe = input.timeframe("240", title="Higher Timeframe")
di_len = input.int(72, "EMA Length")
di_min = input.float(0.03, "DI min")
di_max = input.float(3, "DI max")
// === HEIKIN ASHI VALUES ===
ha_ticker = ticker.heikinashi(syminfo.tickerid)
ha_open = request.security(ha_ticker, ha_timeframe, open)
ha_close = request.security(ha_ticker, ha_timeframe, close)
ha_high = request.security(ha_ticker, ha_timeframe, high)
ha_low = request.security(ha_ticker, ha_timeframe, low)

// Higher Timeframe Heikin Ashi
hf_ha_open = request.security(ha_ticker, hf_timeframe, open, lookahead=barmerge.lookahead_on)
hf_ha_close = request.security(ha_ticker, hf_timeframe, close, lookahead=barmerge.lookahead_on)

hf_open = request.security(syminfo.tickerid, hf_timeframe, open, lookahead=barmerge.lookahead_on)
hf_close = request.security(syminfo.tickerid, hf_timeframe, close, lookahead=barmerge.lookahead_on)

f_detect_color_reversal(ha_open, ha_close) =>
    bull_reversal = ha_close > ha_open and ha_close[1] < ha_open[1] and ha_close[2] < ha_open[2] and  ha_close[3] < ha_open[3]
    bear_reversal = ha_close < ha_open and ha_close[1] > ha_open[1] and ha_close[2] > ha_open[2] and ha_close[3] > ha_open[3]
    [bull_reversal, bear_reversal]

f_higher_tf_trend(hf_ha_open, hf_ha_close) =>
    bull_trend = hf_ha_close > hf_ha_open
    bear_trend = hf_ha_close < hf_ha_open
    [bull_trend, bear_trend]

// Color Reversal
[bull_color_reversal, bear_color_reversal] = f_detect_color_reversal(ha_open, ha_close)

// Higher Timeframe Trend
[hf_bull_trend, hf_bear_trend] = f_higher_tf_trend(hf_ha_open, hf_ha_close)

// DI
ema_val = ta.ema(hf_close, di_len)
dist = hf_close - ema_val
percent_dist = (dist / ema_val) * 100

bull_di = percent_dist > di_min and percent_dist < di_max
bear_di = percent_dist < -di_min and percent_dist > -di_max

bull_reversal = bull_color_reversal and bull_di and hf_bull_trend
bear_reversal = bear_color_reversal and bear_di and hf_bear_trend

plotshape(bull_reversal, title="Bullish Reversal", style=shape.cross, location=location.belowbar, color=color.blue, size=size.tiny)
plotshape(bear_reversal, title="Bearish Reversal", style=shape.cross, location=location.abovebar, color=color.blue, size=size.tiny)

// ALERT
alertcondition(bull_reversal or bear_reversal, title="BUY OR SELL ALERT", message="HA Signal")
alertcondition(bull_reversal, title="BUY ALERT", message="HA Buy Signal")
alertcondition(bear_reversal, title="SELL ALERT", message="HA Sell Signal")