// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cdw1432t

//@version=6
indicator(title = "Disparity", shorttitle = "DI", overlay=false)

// VARIABLES
_timeframe = input.timeframe("60", title="Timeframe")
hf_timeframe = input.timeframe("D", title="Higher Timeframe")
di_len = input.int(75, "SMA Length", minval=1)
di_min = input.float(0.25, "DI min(%)")
di_max = input.float(3, "DI max(%)")
is_label = input.bool(false, "Show Area Labels")

// DATA
_close = request.security(syminfo.tickerid, _timeframe, close,lookahead =  barmerge.lookahead_off)
_ema_val = ta.sma(_close, di_len)
percent_dist = (100 * (close - _ema_val) / _ema_val)

higher_ = request.security(syminfo.tickerid, hf_timeframe, close, lookahead =  barmerge.lookahead_off)
Dema = ta.sma(higher_, di_len)
dema_percent_dist = (100 * (close - Dema) / Dema)

bear_di = (di_min <= percent_dist and percent_dist <= di_max) // 캔들이 평균선 위에서 괴리율, 역)매도 신호
bull_di = (-di_max <= percent_dist and percent_dist <= -di_min) //캔들이 평균선 아래에서 괴리율, 역)매수 신호

potential_supp_buy = 0 < dema_percent_dist and dema_percent_dist < 0.03 // 캔들이 높은 시간대 평균선 근처에 있음. (매수)지지 신호
potential_resis_sell = -0.03 < dema_percent_dist and dema_percent_dist < -0 // 캔들이 높은 시간대 평균선 근처에 있음. (매도)저항 신호

var label percent_dist_label = na
var label dema_percent_dist_label = na

//AREA
body_area_above = close > _ema_val ? close - _ema_val : 0
body_area_below = close < _ema_val ? _ema_val - close : 0

var float area_sum_above = na
var float area_sum_below = na
area_sum_above := nz(area_sum_above)
area_sum_below := nz(area_sum_below)

// = AREA UP
if close > _ema_val
    area_sum_above += body_area_above
else
    if area_sum_above > 0 and is_label
        label.new(bar_index,low,text = str.tostring(area_sum_above*1000, "##.##"),style = label.style_label_up,color = color.new(color.green, 0),textcolor = color.white)
    area_sum_above := 0.0

// = AREA DOWN
if close < _ema_val
    area_sum_below += body_area_below
else
    if area_sum_below > 0 and is_label
        label.new(bar_index,high,text = str.tostring(area_sum_below*1000, "##.##"), style = label.style_label_down,color = color.new(color.red, 0),textcolor = color.white)
    area_sum_below := 0.0

//Plot EMA and AREA
p_close = plot(close, title="Close", color=color.new(color.blue, 0), style=plot.style_linebr, display = display.none-display.status_line)
p_ema = plot(_ema_val, title="EMA", color=color.new(color.red, 0), display = display.all-display.status_line)
p_dema = plot(Dema, title="Higher EMA", color=color.new(color.blue, 0))
fill(p_close, p_dema, color = close > Dema ? color.new(color.green, 90) : color.new(color.red, 90))

//label DI
if barstate.islast
    label.delete(percent_dist_label)
    percent_dist_label := label.new(bar_index+5, _ema_val, str.tostring(percent_dist,"#.###"),xloc = xloc.bar_index, yloc = yloc.price,style=percent_dist >= 0 ? label.style_label_down :label.style_label_up , color=color.new(color.red, 0), textcolor=color.white, size=size.normal)
    label.delete(dema_percent_dist_label)
    dema_percent_dist_label := label.new(bar_index+ 15, Dema, str.tostring(dema_percent_dist, "#.###"),xloc = xloc.bar_index, yloc = yloc.price,style=Dema >= 0 ? label.style_label_down :label.style_label_up , color=color.new(color.blue, 0), textcolor=color.white, size=size.small)


is_local_top = high >= ta.highest(high, 32)
is_local_bottom = low <= ta.lowest(low, 3)

// BUY and SELL Signal
buySignal = bull_di and is_local_bottom  
sellSignal = bear_di and is_local_top 

//Plot Signals
// plot(percent_dist, title="Disparity (Current TF)", color=color.purple)
// plot(dema_percent_dist, title="Disparity (Higher TF)", color=color.orange)

plotshape(potential_supp_buy , title="potential_resis_buy Signal", location=location.belowbar, style=shape.circle, color=color.new(color.green, 66), size=size.tiny)
plotshape(potential_resis_sell , title="potential_resis_buy Signal", location=location.abovebar, style=shape.circle, color=color.new(color.red,66), size=size.tiny)

plotshape(buySignal , title="Buy Signal", location=location.belowbar, style=shape.circle, color=color.rgb(155, 39, 176, 66), size=size.tiny, display = display.all-display.status_line)
plotshape(sellSignal , title="Sell Signal", location=location.abovebar, style=shape.circle, color=color.rgb(155, 39, 176, 66), size=size.tiny, display = display.all-display.status_line)

// ALERTS
alertcondition(sellSignal or buySignal, title="BUY OR SELL ALERT", message="DI Signal")
alertcondition(buySignal, title="BUY ALERT", message="DI Buy Signal")
alertcondition(sellSignal, title="SELL ALERT", message="DI Sell Signal")